package gui;

import iClickerDriver.FrequencyEnum;

import java.io.*;

import javax.swing.*;
import javax.xml.stream.XMLStreamException;

import setting.enumoption.*;

import app.*;

/**
 * Settings window. 
 * @author Junhao
 *
 */
@SuppressWarnings("serial")
public class MySettings extends javax.swing.JFrame {
    
    /**
     * Creates new form MySetting.
     */
    public MySettings(Test test) {
        this.test = test;
        
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings({ })
    private void initComponents() {

        buttonGroupFrequency1 = new javax.swing.ButtonGroup();
        buttonGroupFrequency2 = new javax.swing.ButtonGroup();
        buttonGroupShowResponseGrid = new javax.swing.ButtonGroup();
        buttonGroupShowID = new javax.swing.ButtonGroup();
        buttonGroupPollingTimer = new javax.swing.ButtonGroup();
        buttonGroupMultipleChoiceDisplay = new javax.swing.ButtonGroup();
        buttonGroupShowCorrectAnswer = new javax.swing.ButtonGroup();
        jButtonSetForCourse = new javax.swing.JButton();
        jButtonSetForSession = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanelGeneral = new javax.swing.JPanel();
        jLabelP1CourseNameStatic = new javax.swing.JLabel();
        jLabelP1CourseName = new javax.swing.JLabel();
        jLabelP1InstructorStatic = new javax.swing.JLabel();
        jTextFieldP1Instructor = new javax.swing.JTextField();
        jLabelP1EightCharacters = new javax.swing.JLabel();
        jLabelP1FrequencyCodeStatic = new javax.swing.JLabel();
        jLabelP1FrequencyCode1 = new javax.swing.JLabel();
        jRadioButtonP1FreqencyCode1A = new javax.swing.JRadioButton();
        jRadioButtonP1FreqencyCode1B = new javax.swing.JRadioButton();
        jRadioButtonP1FreqencyCode1C = new javax.swing.JRadioButton();
        jRadioButtonP1FreqencyCode1D = new javax.swing.JRadioButton();
        jLabelP1FrequencyCode2 = new javax.swing.JLabel();
        jRadioButtonP1FreqencyCode2A = new javax.swing.JRadioButton();
        jRadioButtonP1FreqencyCode2B = new javax.swing.JRadioButton();
        jRadioButtonP1FreqencyCode2C = new javax.swing.JRadioButton();
        jRadioButtonP1FreqencyCode2D = new javax.swing.JRadioButton();
        jLabelP1FrequencyAlertStatic = new javax.swing.JLabel();
        jComboBoxP1FrequencyAlert = new javax.swing.JComboBox<String>();
        jLabelP1ResponseGridStatic = new javax.swing.JLabel();
        jRadioButtonP1HideGrid = new javax.swing.JRadioButton();
        jRadioButtonP1ShowGrid = new javax.swing.JRadioButton();
        jRadioButtonP1ShowGridClickerId = new javax.swing.JRadioButton();
        jRadioButtonP1ShowGridStudentId = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jCheckBoxP1ShowChoice = new javax.swing.JCheckBox();
        jCheckBoxP1ShowAttempts = new javax.swing.JCheckBox();
        jPanelPolling = new javax.swing.JPanel();
        jLabelP2PollingTimer = new javax.swing.JLabel();
        jRadioButtonP2Up = new javax.swing.JRadioButton();
        jRadioButtonP2Down = new javax.swing.JRadioButton();
        jComboBoxP2DownTime = new javax.swing.JComboBox<String>();
        jLabelP2PollingMinSec = new javax.swing.JLabel();
        jPanelResults = new javax.swing.JPanel();
        jRadioButtonP3Manual = new javax.swing.JRadioButton();
        jLabelP3CorrectAnswerDisplay = new javax.swing.JLabel();
        jRadioButtonP3Auto = new javax.swing.JRadioButton();
        jLabelP3PreAssigned = new javax.swing.JLabel();
        jPanelScoring = new javax.swing.JPanel();
        jLabelP4ParticipationPointsStatic = new javax.swing.JLabel();
        jLabelP4SessionParticipationPointsStatic = new javax.swing.JLabel();
        jTextFieldP4SessionParticipationPoints = new javax.swing.JTextField();
        jLabelP4PointsAreAwardedStatic = new javax.swing.JLabel();
        jLabelP4ParticipationPointsRequirementStatic = new javax.swing.JLabel();
        jComboBoxP4ParticipationPointsRequirement = new javax.swing.JComboBox<String>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelP4PerformancePointsStatic = new javax.swing.JLabel();
        jLabelP4PointsForRespondingStatic = new javax.swing.JLabel();
        jTextFieldP4PointsForResponding = new javax.swing.JTextField();
        jLabelP4PointsForCorrectStatic = new javax.swing.JLabel();
        jTextFieldP4PointsForCorrect = new javax.swing.JTextField();
        jLabelP4EachQuestionStatic = new javax.swing.JLabel();
        jLabelP4TotalPointStatic = new javax.swing.JLabel();
        jCheckBoxP4TotalLimitEnabled = new javax.swing.JCheckBox();
        jTextFieldP4TotalLimit = new javax.swing.JTextField();
        jLabelP4ParticipationBarValue = new javax.swing.JLabel();
        jTextFieldP4ParticipationBarValue = new javax.swing.JTextField();
        jLabelP4ParticipationBarPercent = new javax.swing.JLabel();
        jTextFieldP4PerformanceBarValue = new javax.swing.JTextField();
        jLabelP4PerformanceBarValue = new javax.swing.JLabel();
        jLabelP4PerformanceBarPercent = new javax.swing.JLabel();
        jPanelBaseDisplay = new javax.swing.JPanel();
        jLabelP5A2EDisplay = new javax.swing.JLabel();
        jRadioButtonP5Percentage = new javax.swing.JRadioButton();
        jRadioButtonP5Number = new javax.swing.JRadioButton();
        jRadioButtonP5Alternating = new javax.swing.JRadioButton();
        jLabelP5Alternate = new javax.swing.JLabel();
        jComboBoxP5AlternateTime = new javax.swing.JComboBox<String>();
        jLabelP5Second = new javax.swing.JLabel();
        jPanelDemographics = new javax.swing.JPanel();
        jLabelP6AvailableQuestions = new javax.swing.JLabel();
        jLabelP6SelectedQuestions = new javax.swing.JLabel();
        jScrollPaneP6AvailableQuestions = new javax.swing.JScrollPane();
        jListP6AvailableQuestions = new javax.swing.JList<String>();
        jButtonP6Select = new javax.swing.JButton();
        jScrollPaneP6SelectedQuestions = new javax.swing.JScrollPane();
        jListP6SelectedQuestions = new javax.swing.JList<String>();
        jButtonP6Unselected = new javax.swing.JButton();
        jButtonP6New = new javax.swing.JButton();
        jButtonP6Edit = new javax.swing.JButton();
        jButtonP6Import = new javax.swing.JButton();
        jButtonP6Delete = new javax.swing.JButton();
        jButtonP6MoveUp = new javax.swing.JButton();
        jButtonP6MoveDown = new javax.swing.JButton();
        jCheckBoxP6AutoAdvance = new javax.swing.JCheckBox();
        jComboBoxP6AutoAdvanceTime = new javax.swing.JComboBox<String>();
        jLabelP6DemographicsMinSec = new javax.swing.JLabel();

        setTitle("My Settings");
        setResizable(false);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButtonSetForCourse.setText("Set for Course");
        jButtonSetForCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonSetForCourseActionPerformed(evt);
				} catch (IOException e) {
					e.printStackTrace();
				} catch (XMLStreamException e) {
					e.printStackTrace();
				}
            }
        });

        jButtonSetForSession.setText("Set for Session");
        jButtonSetForSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetForSessionActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelP1CourseNameStatic.setText("Course Name:");

        jLabelP1CourseName.setText("ABC");

        jLabelP1InstructorStatic.setText("Instrcutor's Remote ID:");

        jLabelP1EightCharacters.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jLabelP1EightCharacters.setText("(Eight character code on back of remote)");

        jLabelP1FrequencyCodeStatic.setText("Frequency Code");

        jLabelP1FrequencyCode1.setText("Subfrequency Code 1:");

        buttonGroupFrequency1.add(jRadioButtonP1FreqencyCode1A);
        jRadioButtonP1FreqencyCode1A.setSelected(true);
        jRadioButtonP1FreqencyCode1A.setText("A");

        buttonGroupFrequency1.add(jRadioButtonP1FreqencyCode1B);
        jRadioButtonP1FreqencyCode1B.setText("B");

        buttonGroupFrequency1.add(jRadioButtonP1FreqencyCode1C);
        jRadioButtonP1FreqencyCode1C.setText("C");

        buttonGroupFrequency1.add(jRadioButtonP1FreqencyCode1D);
        jRadioButtonP1FreqencyCode1D.setText("D");

        jLabelP1FrequencyCode2.setText("Subfrequency Code 2");

        buttonGroupFrequency2.add(jRadioButtonP1FreqencyCode2A);
        jRadioButtonP1FreqencyCode2A.setSelected(true);
        jRadioButtonP1FreqencyCode2A.setText("A");

        buttonGroupFrequency2.add(jRadioButtonP1FreqencyCode2B);
        jRadioButtonP1FreqencyCode2B.setText("B");

        buttonGroupFrequency2.add(jRadioButtonP1FreqencyCode2C);
        jRadioButtonP1FreqencyCode2C.setText("C");

        buttonGroupFrequency2.add(jRadioButtonP1FreqencyCode2D);
        jRadioButtonP1FreqencyCode2D.setText("D");

        jLabelP1FrequencyAlertStatic.setText("When the frequency code is not set to default value AA, show an alert message:");
        jLabelP1FrequencyAlertStatic.setVisible(false);
        
        jComboBoxP1FrequencyAlert.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "until manually closed", "for 30 seconds", "for 15 seconds", "for 5 seconds", "not at all" }));
        jComboBoxP1FrequencyAlert.setVisible(false);
        
        jLabelP1ResponseGridStatic.setText("Response Grid");

        buttonGroupShowResponseGrid.add(jRadioButtonP1HideGrid);
        jRadioButtonP1HideGrid.setSelected(true);
        jRadioButtonP1HideGrid.setText("Hide response grid");
        jRadioButtonP1HideGrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonP1HideGridActionPerformed(evt);
            }
        });

        buttonGroupShowResponseGrid.add(jRadioButtonP1ShowGrid);
        jRadioButtonP1ShowGrid.setText("Show response grid");
        jRadioButtonP1ShowGrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonP1ShowGridActionPerformed(evt);
            }
        });

        buttonGroupShowID.add(jRadioButtonP1ShowGridClickerId);
        jRadioButtonP1ShowGridClickerId.setText("Show clicker ID in response grid");

        buttonGroupShowID.add(jRadioButtonP1ShowGridStudentId);
        jRadioButtonP1ShowGridStudentId.setText("Show student ID in response grid");

        jCheckBoxP1ShowChoice.setText("Show choice");

        jCheckBoxP1ShowAttempts.setText("Show number of attampts");

        org.jdesktop.layout.GroupLayout jPanelGeneralLayout = new org.jdesktop.layout.GroupLayout(jPanelGeneral);
        jPanelGeneral.setLayout(jPanelGeneralLayout);
        jPanelGeneralLayout.setHorizontalGroup(
            jPanelGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator3)
                    .add(jSeparator4)
                    .add(jPanelGeneralLayout.createSequentialGroup()
                        .add(jPanelGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanelGeneralLayout.createSequentialGroup()
                                .add(jLabelP1CourseNameStatic)
                                .add(18, 18, 18)
                                .add(jLabelP1CourseName))
                            .add(jPanelGeneralLayout.createSequentialGroup()
                                .add(jLabelP1InstructorStatic)
                                .add(18, 18, 18)
                                .add(jTextFieldP1Instructor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabelP1EightCharacters))
                            .add(jLabelP1FrequencyCodeStatic)
                            .add(jLabelP1ResponseGridStatic)
                            .add(jPanelGeneralLayout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jPanelGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jPanelGeneralLayout.createSequentialGroup()
                                        .add(jPanelGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabelP1FrequencyCode1)
                                            .add(jLabelP1FrequencyCode2))
                                        .add(18, 18, 18)
                                        .add(jPanelGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jPanelGeneralLayout.createSequentialGroup()
                                                .add(jRadioButtonP1FreqencyCode1A)
                                                .add(18, 18, 18)
                                                .add(jRadioButtonP1FreqencyCode1B)
                                                .add(18, 18, 18)
                                                .add(jRadioButtonP1FreqencyCode1C)
                                                .add(18, 18, 18)
                                                .add(jRadioButtonP1FreqencyCode1D))
                                            .add(jPanelGeneralLayout.createSequentialGroup()
                                                .add(jRadioButtonP1FreqencyCode2A)
                                                .add(18, 18, 18)
                                                .add(jRadioButtonP1FreqencyCode2B)
                                                .add(18, 18, 18)
                                                .add(jRadioButtonP1FreqencyCode2C)
                                                .add(18, 18, 18)
                                                .add(jRadioButtonP1FreqencyCode2D))))
                                    .add(jLabelP1FrequencyAlertStatic)
                                    .add(jPanelGeneralLayout.createSequentialGroup()
                                        .add(10, 10, 10)
                                        .add(jComboBoxP1FrequencyAlert, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jRadioButtonP1HideGrid)
                                    .add(jRadioButtonP1ShowGrid)
                                    .add(jPanelGeneralLayout.createSequentialGroup()
                                        .add(21, 21, 21)
                                        .add(jPanelGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jRadioButtonP1ShowGridStudentId)
                                            .add(jRadioButtonP1ShowGridClickerId)
                                            .add(jCheckBoxP1ShowChoice)
                                            .add(jCheckBoxP1ShowAttempts))))))
                        .add(0, 97, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelGeneralLayout.setVerticalGroup(
            jPanelGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelGeneralLayout.createSequentialGroup()
                .add(36, 36, 36)
                .add(jPanelGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelP1CourseNameStatic)
                    .add(jLabelP1CourseName))
                .add(18, 18, 18)
                .add(jPanelGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelP1InstructorStatic)
                    .add(jTextFieldP1Instructor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelP1EightCharacters))
                .add(18, 18, 18)
                .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelP1FrequencyCodeStatic)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanelGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelP1FrequencyCode1)
                    .add(jRadioButtonP1FreqencyCode1A)
                    .add(jRadioButtonP1FreqencyCode1B)
                    .add(jRadioButtonP1FreqencyCode1C)
                    .add(jRadioButtonP1FreqencyCode1D))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanelGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelP1FrequencyCode2)
                    .add(jRadioButtonP1FreqencyCode2A)
                    .add(jRadioButtonP1FreqencyCode2B)
                    .add(jRadioButtonP1FreqencyCode2C)
                    .add(jRadioButtonP1FreqencyCode2D))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelP1FrequencyAlertStatic)
                .add(9, 9, 9)
                .add(jComboBoxP1FrequencyAlert, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jSeparator4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabelP1ResponseGridStatic)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jRadioButtonP1HideGrid)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButtonP1ShowGrid)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButtonP1ShowGridClickerId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButtonP1ShowGridStudentId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCheckBoxP1ShowChoice)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCheckBoxP1ShowAttempts)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        
        jTabbedPane3.addTab("General", jPanelGeneral);

        jLabelP2PollingTimer.setText("Polling Timer");

        buttonGroupPollingTimer.add(jRadioButtonP2Up);
        jRadioButtonP2Up.setText("Count up from 0 seconds");

        buttonGroupPollingTimer.add(jRadioButtonP2Down);
        jRadioButtonP2Down.setText("Count down from");
        
        jComboBoxP2DownTime.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "00:15", "00:30", "00:45", "01:00", "01:15", "01:30", "01:45", "02:00", "02:15", "02:30", "02:45", "03:00", "03:15", "03:30", "03:45", "04:00", " " }));
        jComboBoxP2DownTime.setSelectedIndex(1);

        jLabelP2PollingMinSec.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jLabelP2PollingMinSec.setText("(min:sec)");

        org.jdesktop.layout.GroupLayout jPanelPollingLayout = new org.jdesktop.layout.GroupLayout(jPanelPolling);
        jPanelPolling.setLayout(jPanelPollingLayout);
        jPanelPollingLayout.setHorizontalGroup(
            jPanelPollingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPollingLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelPollingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelPollingLayout.createSequentialGroup()
                        .add(jRadioButtonP2Up)
                        .add(18, 18, 18)
                        .add(jRadioButtonP2Down)
                        .add(18, 18, 18)
                        .add(jComboBoxP2DownTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabelP2PollingMinSec))
                    .add(jLabelP2PollingTimer))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanelPollingLayout.setVerticalGroup(
            jPanelPollingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPollingLayout.createSequentialGroup()
                .add(35, 35, 35)
                .add(jLabelP2PollingTimer)
                .add(18, 18, 18)
                .add(jPanelPollingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButtonP2Up)
                    .add(jRadioButtonP2Down)
                    .add(jComboBoxP2DownTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelP2PollingMinSec))
                .addContainerGap(385, Short.MAX_VALUE))
        );


        //jTabbedPane3.addTab("Polling", jPanelPolling);

        jLabelP3CorrectAnswerDisplay.setText("Correct answer display");

        jLabelP3PreAssigned.setText("For questions with pre-assigned correct answers:");

        buttonGroupShowCorrectAnswer.add(jRadioButtonP3Auto);
        jRadioButtonP3Auto.setText("Show correct answers when polling is stopped");

        buttonGroupShowCorrectAnswer.add(jRadioButtonP3Manual);
        jRadioButtonP3Manual.setText("Hide correct answers until displayed manually");
        
        org.jdesktop.layout.GroupLayout jPanelResultsLayout = new org.jdesktop.layout.GroupLayout(jPanelResults);
        jPanelResults.setLayout(jPanelResultsLayout);
        jPanelResultsLayout.setHorizontalGroup(
            jPanelResultsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelResultsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelResultsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelP3CorrectAnswerDisplay)
                    .add(jPanelResultsLayout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jPanelResultsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelP3PreAssigned)
                            .add(jPanelResultsLayout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jPanelResultsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jRadioButtonP3Manual)
                                    .add(jRadioButtonP3Auto))))))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanelResultsLayout.setVerticalGroup(
            jPanelResultsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelResultsLayout.createSequentialGroup()
                .add(31, 31, 31)
                .add(jLabelP3CorrectAnswerDisplay)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabelP3PreAssigned)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jRadioButtonP3Auto)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButtonP3Manual)
                .addContainerGap(353, Short.MAX_VALUE))
        );

        //jTabbedPane3.addTab("Results", jPanelResults);
        
        jLabelP4ParticipationPointsStatic.setText("Participation points");

        jLabelP4SessionParticipationPointsStatic.setText("Session participation points:");

        jLabelP4PointsAreAwardedStatic.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jLabelP4PointsAreAwardedStatic.setText("Points are awarded all-or-nothing for the session");

        jLabelP4ParticipationPointsRequirementStatic.setText("To earn participation points students must respond to:");

        jComboBoxP4ParticipationPointsRequirement.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "100% of the questions", "all but one question", "at least 75% of the questions", "at least 50% of the questions", "at least one question" }));

        jLabelP4ParticipationBarValue.setText("Participation bar value");

        jLabelP4ParticipationBarPercent.setText("%");
        
        jLabelP4PerformancePointsStatic.setText("Performace points");

        jLabelP4PointsForRespondingStatic.setText("Points for responding:      ");

        jLabelP4PointsForCorrectStatic.setText("Points for correct response:");

        jLabelP4EachQuestionStatic.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jLabelP4EachQuestionStatic.setText("} Each question is worth the");

        jLabelP4TotalPointStatic.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        jLabelP4TotalPointStatic.setText("total of the point values below");

        jCheckBoxP4TotalLimitEnabled.setText("Limit the total performance points earned in a session to a maximum of:");
        jCheckBoxP4TotalLimitEnabled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxP4TotalLimitEnabledActionPerformed(evt);
            }
        });

        jLabelP4PerformanceBarPercent.setText("Performance bar value");

        jLabelP4PerformanceBarValue.setText("%");

        org.jdesktop.layout.GroupLayout jPanelScoringLayout = new org.jdesktop.layout.GroupLayout(jPanelScoring);
        jPanelScoring.setLayout(jPanelScoringLayout);
        jPanelScoringLayout.setHorizontalGroup(
            jPanelScoringLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelScoringLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelScoringLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator2)
                    .add(jPanelScoringLayout.createSequentialGroup()
                        .add(jPanelScoringLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelP4ParticipationPointsStatic)
                            .add(jLabelP4PerformancePointsStatic)
                            .add(jPanelScoringLayout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jPanelScoringLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanelScoringLayout.createSequentialGroup()
                                        .add(jLabelP4ParticipationPointsRequirementStatic)
                                        .add(18, 18, 18)
                                        .add(jComboBoxP4ParticipationPointsRequirement, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanelScoringLayout.createSequentialGroup()
                                        .add(jLabelP4SessionParticipationPointsStatic)
                                        .add(18, 18, 18)
                                        .add(jTextFieldP4SessionParticipationPoints, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(18, 18, 18)
                                        .add(jLabelP4PointsAreAwardedStatic))
                                    .add(jPanelScoringLayout.createSequentialGroup()
                                        .add(jPanelScoringLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(jPanelScoringLayout.createSequentialGroup()
                                                .add(jLabelP4PointsForRespondingStatic)
                                                .add(18, 18, 18)
                                                .add(jTextFieldP4PointsForResponding, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(jPanelScoringLayout.createSequentialGroup()
                                                .add(jLabelP4PointsForCorrectStatic)
                                                .add(18, 18, 18)
                                                .add(jTextFieldP4PointsForCorrect)))
                                        .add(18, 18, 18)
                                        .add(jPanelScoringLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabelP4EachQuestionStatic)
                                            .add(jLabelP4TotalPointStatic)))))
                            .add(jPanelScoringLayout.createSequentialGroup()
                                .add(jCheckBoxP4TotalLimitEnabled)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jTextFieldP4TotalLimit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanelScoringLayout.createSequentialGroup()
                                .add(jLabelP4ParticipationBarValue)
                                .add(18, 18, 18)
                                .add(jTextFieldP4ParticipationBarValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabelP4ParticipationBarPercent))
                            .add(jPanelScoringLayout.createSequentialGroup()
                                .add(jLabelP4PerformanceBarPercent)
                                .add(18, 18, 18)
                                .add(jTextFieldP4PerformanceBarValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabelP4PerformanceBarValue)))
                        .add(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelScoringLayout.setVerticalGroup(
            jPanelScoringLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelScoringLayout.createSequentialGroup()
                .add(36, 36, 36)
                .add(jLabelP4ParticipationPointsStatic)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanelScoringLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelP4SessionParticipationPointsStatic)
                    .add(jTextFieldP4SessionParticipationPoints, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelP4PointsAreAwardedStatic))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanelScoringLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelP4ParticipationPointsRequirementStatic)
                    .add(jComboBoxP4ParticipationPointsRequirement, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanelScoringLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelP4ParticipationBarValue)
                    .add(jTextFieldP4ParticipationBarValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelP4ParticipationBarPercent))
                .add(18, 18, 18)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanelScoringLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelScoringLayout.createSequentialGroup()
                        .add(jLabelP4PerformancePointsStatic)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanelScoringLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabelP4PointsForRespondingStatic)
                            .add(jTextFieldP4PointsForResponding, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabelP4EachQuestionStatic))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanelScoringLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelScoringLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabelP4PointsForCorrectStatic)
                        .add(jTextFieldP4PointsForCorrect, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabelP4TotalPointStatic))
                .add(18, 18, 18)
                .add(jPanelScoringLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCheckBoxP4TotalLimitEnabled)
                    .add(jTextFieldP4TotalLimit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanelScoringLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelP4PerformanceBarPercent)
                    .add(jTextFieldP4PerformanceBarValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelP4PerformanceBarValue))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Scoring", jPanelScoring);

        jLabelP5A2EDisplay.setText("Multiple choice (A-E) display");

        buttonGroupMultipleChoiceDisplay.add(jRadioButtonP5Percentage);
        jRadioButtonP5Percentage.setText("Show the percentage of votes for each answer choice");
        jRadioButtonP5Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonP5PercentageActionPerformed(evt);
            }
        });
        
        buttonGroupMultipleChoiceDisplay.add(jRadioButtonP5Number);
        jRadioButtonP5Number.setText("Show the number of votes for each answer choice");
        jRadioButtonP5Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonP5NumberActionPerformed(evt);
            }
        });
        
        buttonGroupMultipleChoiceDisplay.add(jRadioButtonP5Alternating);
        jRadioButtonP5Alternating.setText("Show the percentage and number of votes for each answer choice (alternating)");
        jRadioButtonP5Alternating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonP5AlternatingActionPerformed(evt);
            }
        });

        jLabelP5Alternate.setText("Alternate the display every");

        jComboBoxP5AlternateTime.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "2", "5", "10" }));

        jLabelP5Second.setText("seconds");

        org.jdesktop.layout.GroupLayout jPanelBaseDisplayLayout = new org.jdesktop.layout.GroupLayout(jPanelBaseDisplay);
        jPanelBaseDisplay.setLayout(jPanelBaseDisplayLayout);
        jPanelBaseDisplayLayout.setHorizontalGroup(
            jPanelBaseDisplayLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBaseDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelBaseDisplayLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelP5A2EDisplay)
                    .add(jPanelBaseDisplayLayout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jPanelBaseDisplayLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jRadioButtonP5Number)
                            .add(jRadioButtonP5Percentage)
                            .add(jRadioButtonP5Alternating)
                            .add(jPanelBaseDisplayLayout.createSequentialGroup()
                                .add(21, 21, 21)
                                .add(jLabelP5Alternate)
                                .add(18, 18, 18)
                                .add(jComboBoxP5AlternateTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabelP5Second)))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanelBaseDisplayLayout.setVerticalGroup(
            jPanelBaseDisplayLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBaseDisplayLayout.createSequentialGroup()
                .add(40, 40, 40)
                .add(jLabelP5A2EDisplay)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jRadioButtonP5Percentage)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButtonP5Number)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButtonP5Alternating)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanelBaseDisplayLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelP5Alternate)
                    .add(jComboBoxP5AlternateTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelP5Second))
                .addContainerGap(319, Short.MAX_VALUE))
        );

        //jTabbedPane3.addTab("Base Display", jPanelBaseDisplay);

        jLabelP6AvailableQuestions.setText("Available questions:");

        jLabelP6SelectedQuestions.setText("Selected questions:");

        jListP6AvailableQuestions.setModel(new javax.swing.DefaultListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i];} 
        });
    
        jScrollPaneP6AvailableQuestions.setViewportView(jListP6AvailableQuestions);

        jButtonP6Select.setText(">");
        jButtonP6Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP6SelectActionPerformed(evt);
            }
        });

        jListP6SelectedQuestions.setModel(new javax.swing.DefaultListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i];} 
        });
        
        jScrollPaneP6SelectedQuestions.setViewportView(jListP6SelectedQuestions);

        jButtonP6Unselected.setText("<");
        jButtonP6Unselected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP6UnselectedActionPerformed(evt);
            }
        });

        jButtonP6New.setText("New");
        jButtonP6New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP6NewActionPerformed(evt);
            }
        });

        jButtonP6Edit.setText("Edit");
        jButtonP6Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP6EditActionPerformed(evt);
            }
        });

        jButtonP6Import.setText("Import");
        jButtonP6Import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP6ImportActionPerformed(evt);
            }
        });
        jButtonP6Import.setVisible(false);

        jButtonP6Delete.setText("Delete");
        jButtonP6Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP6DeleteActionPerformed(evt);
            }
        });

        jButtonP6MoveUp.setText("Move Up");
        jButtonP6MoveUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP6MoveUpActionPerformed(evt);
            }
        });

        jButtonP6MoveDown.setText("Move Down");
        jButtonP6MoveDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP6MoveDownActionPerformed(evt);
            }
        });

        jCheckBoxP6AutoAdvance.setText("Auto advance questions every:");
        jCheckBoxP6AutoAdvance.setVisible(false);
        jCheckBoxP6AutoAdvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxP6AutoAdvanceActionPerformed(evt);
            }
        });        

        jComboBoxP6AutoAdvanceTime.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "00:10", "00:20", "00:30", "00:40", "00:50", "01:00", "01:10", "01:20", "01:30", "01:40", "01:50", "02:00", "02:10", "02:20", "02:30", "02:40", "02:50", "03:00", "03:10", "03:20", "03:30", "03:40", "03:50", "04:00" }));
        jComboBoxP6AutoAdvanceTime.setSelectedIndex(2);
        jComboBoxP6AutoAdvanceTime.setToolTipText("");
        jComboBoxP6AutoAdvanceTime.setVisible(false);
        
        jLabelP6DemographicsMinSec.setText("(min:sec)");
        jLabelP6DemographicsMinSec.setVisible(false);
        
        org.jdesktop.layout.GroupLayout jPanelDemographicsLayout = new org.jdesktop.layout.GroupLayout(jPanelDemographics);
        jPanelDemographics.setLayout(jPanelDemographicsLayout);
        jPanelDemographicsLayout.setHorizontalGroup(
            jPanelDemographicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelDemographicsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelDemographicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelDemographicsLayout.createSequentialGroup()
                        .add(jCheckBoxP6AutoAdvance)
                        .add(18, 18, 18)
                        .add(jComboBoxP6AutoAdvanceTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabelP6DemographicsMinSec)
                        .addContainerGap())
                    .add(jPanelDemographicsLayout.createSequentialGroup()
                        .add(jPanelDemographicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelP6AvailableQuestions)
                            .add(jPanelDemographicsLayout.createSequentialGroup()
                                .add(jScrollPaneP6AvailableQuestions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 247, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jPanelDemographicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jButtonP6Select, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .add(jButtonP6Unselected, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .add(jPanelDemographicsLayout.createSequentialGroup()
                                .add(jButtonP6New)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonP6Edit)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonP6Delete)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonP6Import)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 14, Short.MAX_VALUE)
                        .add(jPanelDemographicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPaneP6SelectedQuestions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 247, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabelP6SelectedQuestions)
                            .add(jPanelDemographicsLayout.createSequentialGroup()
                                .add(jButtonP6MoveUp)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonP6MoveDown)))
                        .addContainerGap())))
        );
        jPanelDemographicsLayout.setVerticalGroup(
            jPanelDemographicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelDemographicsLayout.createSequentialGroup()
                .add(jPanelDemographicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelDemographicsLayout.createSequentialGroup()
                        .add(48, 48, 48)
                        .add(jPanelDemographicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jScrollPaneP6SelectedQuestions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 248, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanelDemographicsLayout.createSequentialGroup()
                                .add(jPanelDemographicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabelP6AvailableQuestions)
                                    .add(jLabelP6SelectedQuestions))
                                .add(29, 29, 29)
                                .add(jScrollPaneP6AvailableQuestions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 248, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jPanelDemographicsLayout.createSequentialGroup()
                        .add(187, 187, 187)
                        .add(jButtonP6Select)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jButtonP6Unselected)))
                .add(18, 18, 18)
                .add(jPanelDemographicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelDemographicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jButtonP6New)
                        .add(jButtonP6Edit)
                        .add(jButtonP6Import)
                        .add(jButtonP6Delete))
                    .add(jPanelDemographicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jButtonP6MoveUp)
                        .add(jButtonP6MoveDown)))
                .add(18, 18, 18)
                .add(jPanelDemographicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCheckBoxP6AutoAdvance)
                    .add(jComboBoxP6AutoAdvanceTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelP6DemographicsMinSec))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        //jTabbedPane3.addTab("Demographics", jPanelDemographics);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jTabbedPane3)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jButtonSetForCourse)
                        .add(18, 18, 18)
                        .add(jButtonSetForSession)
                        .add(18, 18, 18)
                        .add(jButtonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonSetForCourse)
                    .add(jButtonSetForSession)
                    .add(jButtonCancel))
                .addContainerGap())
        );
        
        pack();
    }// </editor-fold>

    private void jRadioButtonP1HideGridActionPerformed(java.awt.event.ActionEvent evt) {
        // General Hide response grid
    	
        this.jRadioButtonP1ShowGridClickerId.setEnabled(false);
        this.jRadioButtonP1ShowGridStudentId.setEnabled(false);
        this.jCheckBoxP1ShowChoice.setEnabled(false);
        this.jCheckBoxP1ShowAttempts.setEnabled(false);
    }

    private void jRadioButtonP1ShowGridActionPerformed(java.awt.event.ActionEvent evt) {
        // General Show response grid
    	
        this.jRadioButtonP1ShowGridClickerId.setEnabled(true);
        this.jRadioButtonP1ShowGridStudentId.setEnabled(true);
        this.jCheckBoxP1ShowChoice.setEnabled(true);
        this.jCheckBoxP1ShowAttempts.setEnabled(true);
    }
    
    private void jCheckBoxP4TotalLimitEnabledActionPerformed(java.awt.event.ActionEvent evt) {
        // Scoring Limit the total
    	
        if (this.jCheckBoxP4TotalLimitEnabled.isSelected()) {
            this.jTextFieldP4TotalLimit.setEnabled(true);
        } else {
            this.jTextFieldP4TotalLimit.setEnabled(false);
        }
    }
    
    private void jRadioButtonP5PercentageActionPerformed(java.awt.event.ActionEvent evt) {
        // Base display Multiple choice display percentage
    	
    	this.jLabelP5Alternate.setEnabled(false);
    	this.jComboBoxP5AlternateTime.setEnabled(false);
    	this.jLabelP5Second.setEnabled(false);
    }

    private void jRadioButtonP5NumberActionPerformed(java.awt.event.ActionEvent evt) {
        // Base display Multiple choice display number
    	
    	this.jLabelP5Alternate.setEnabled(false);
    	this.jComboBoxP5AlternateTime.setEnabled(false);
    	this.jLabelP5Second.setEnabled(false);    	
    }
    
    private void jRadioButtonP5AlternatingActionPerformed(java.awt.event.ActionEvent evt) {
        // Base display Multiple choice display percentage and number
    	
    	this.jLabelP5Alternate.setEnabled(true);
    	this.jComboBoxP5AlternateTime.setEnabled(true);
    	this.jLabelP5Second.setEnabled(true);
    }
    
    private void jButtonP6SelectActionPerformed(java.awt.event.ActionEvent evt) {
        // Demographics >
    }

    private void jButtonP6UnselectedActionPerformed(java.awt.event.ActionEvent evt) {
    	// Demographics <
    }

    private void jButtonP6NewActionPerformed(java.awt.event.ActionEvent evt) {
    	// Demographics New
    }

    private void jButtonP6EditActionPerformed(java.awt.event.ActionEvent evt) {
        // Demographics Edit
    }

    private void jButtonP6DeleteActionPerformed(java.awt.event.ActionEvent evt) {
        // Demographics Delete
    }

    private void jButtonP6ImportActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO 
    }

    private void jButtonP6MoveUpActionPerformed(java.awt.event.ActionEvent evt) {
    	// Move up
    }

    private void jButtonP6MoveDownActionPerformed(java.awt.event.ActionEvent evt) {
    	// Move down
    }
    
    private void jCheckBoxP6AutoAdvanceActionPerformed(java.awt.event.ActionEvent evt) {
    	// Demographics Auto advance checkbox
    }    
    
    private void jButtonSetForCourseActionPerformed(java.awt.event.ActionEvent evt) throws IOException, XMLStreamException {
        // Button Set for course

    	if (checkFieldsLegal() == true) {
            this.writeConfiguration();
            this.storeConfiguration();
            this.setVisible(false);
    	}
    }

    private void jButtonSetForSessionActionPerformed(java.awt.event.ActionEvent evt) {
        // Button Set for session
    	
    	if (checkFieldsLegal() == true) {
    		this.writeConfiguration();
    		this.setVisible(false);
    	}
    }

    /**
     * Check if the fields entered is legal.
     * @return true if legal, false otherwise.
     */
    private boolean checkFieldsLegal() {
    	// Check instructor Id.
    	if (checkInstructorId() == false) {
    		return false;
    	}
    	
    	// Check scoring.
    	if (checkScoring() == false) {
    		return false;
    	}
    	
    	return true;
    }
    
    /**
     * Check if the instructor Id entered is legal.
     * @return true if legal, false otherwise.
     */
    private boolean checkInstructorId() {
    	String instructorId = this.jTextFieldP1Instructor.getText();
    	
    	// Check if instructor id is set.
    	if (instructorId.length() == 0) {
    		return true;
    	}
    	
    	// Check number of characters.
    	if (instructorId.length() != 8) {
    		JOptionPane.showMessageDialog(this, "A remote ID should have exactly eight characters.", "Incorrect number of characters!", JOptionPane.ERROR_MESSAGE);
    		return false;
    	}
    	
    	instructorId = instructorId.toUpperCase();
    	
    	// Check if there is non-alphanumeric characters.
    	for (char e : instructorId.toCharArray()) {
    		if (!Character.isLetter(e) && !Character.isDigit(e)) {
    			JOptionPane.showMessageDialog(this, "A remote ID should only contain A-Z and 0-9.", "Illegal character detected!", JOptionPane.ERROR_MESSAGE);
    			return false;
    		}
    	}
    	
    	// Check if the forth byte is the Xor of first three bytes.
        int id1 = Integer.valueOf(instructorId.substring(0, 2), 16);
        int id2 = Integer.valueOf(instructorId.substring(2, 4), 16);
        int id3 = Integer.valueOf(instructorId.substring(4, 6), 16);
        int id4 = id1 ^ id2 ^ id3;
    	int id4Test = Integer.valueOf(instructorId.substring(6, 8), 16);
    	
    	if (id4 != id4Test) {
			JOptionPane.showMessageDialog(this, "This is not a correct remote Id. Please check again.", "Incorrect ID detected!", JOptionPane.ERROR_MESSAGE);
			return false;
    	}
    	
    	return true;
    }
    
    /**
     * Given a string representing a non-negative integer number, check if it contains any illegal character 
     * and if it is a negative number. 
     * @param text a string representing a positive integer number.
     * @return true if text is legal, false if illegal.
     */
    private boolean checkScore(String text) {
    	if (text.equals("")) return true;
    	
    	for (char e : text.toCharArray()) {
    		if (!Character.isDigit(e)) {
    			JOptionPane.showMessageDialog(this, "Illegal characters in session participation points.", "Illegal character detected!", JOptionPane.ERROR_MESSAGE);
    			return false;
    		}
    	}
    	
    	// Check if number is legal.
    	int sessionParticipationPointsInt = Integer.parseInt(text);
    	if (sessionParticipationPointsInt < 0) {
			JOptionPane.showMessageDialog(this, "Negative number detected in session participation points.", "Illegal number detected!", JOptionPane.ERROR_MESSAGE);
			return false;
    	}
		
    	return true;
    }
    
    /**
     * Given a string representing a non-negative integer number smaller than 101, check if it contains 
     * any illegal character and its range.
     * @param text a string representing a percentage number (a non-negative integer number greater than smaller than 101).
     * @return true if text is legal, false if illegal.
     */
    private boolean checkPercentage(String text) {
    	if (checkScore(text) == false) return false;
    	
    	// Check if number is smaller than 101.
    	int sessionParticipationPointsInt = Integer.parseInt(text);
    	if (sessionParticipationPointsInt > 100) {
			JOptionPane.showMessageDialog(this, "Number larger than 100 detected for a percentage number.", "Illegal number detected!", JOptionPane.ERROR_MESSAGE);
			return false;
    	}
    	
    	return true;
    }
    
    /**
     * Check if the scores entered is legal.
     * @return true if legal, false otherwise.
     */
    private boolean checkScoring() {
    	// Check session participation points.
	    if (this.checkScore(this.jTextFieldP4SessionParticipationPoints.getText()) == false) return false;

	    // Check points for responding.
	    if (this.checkScore(this.jTextFieldP4PointsForResponding.getText()) == false) return false;
	    	
    	// Check points for correct responding.
    	if (this.checkScore(this.jTextFieldP4PointsForCorrect.getText()) == false) return false;
	    	    	
    	// If there is a limit for session participation points, check.
    	if (this.jCheckBoxP4TotalLimitEnabled.isSelected()) {
	    	if (this.checkScore(this.jTextFieldP4TotalLimit.getText()) == false) return false;
    	}
    	
    	// Check participation bar value
    	if (this.checkPercentage(this.jTextFieldP4ParticipationBarValue.getText()) == false) return false;
    	
    	// Check performance bar value
    	if (this.checkPercentage(this.jTextFieldP4PerformanceBarValue.getText()) == false) return false;
    	
    	return true;
    }
    
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {
        // Button Cancel
    	
        this.setVisible(false);
    }

    /**
     * Load configuration from session fields when MySettings window is launched.
     */
    public void readConfiguration() {
    	// General
    	
    	this.jLabelP1CourseName.setText(this.test.getCourse().getCourseName());
    	this.jTextFieldP1Instructor.setText(this.test.getCourse().getInstructorID());
    	
    	this.buttonGroupFrequency1.clearSelection();
    	switch (this.test.getCourse().getFrequencyEnum1()) {
    	case A:		this.jRadioButtonP1FreqencyCode1A.doClick();	break;
    	case B:		this.jRadioButtonP1FreqencyCode1B.doClick();	break;
    	case C:		this.jRadioButtonP1FreqencyCode1C.doClick();	break;
    	default:	this.jRadioButtonP1FreqencyCode1D.doClick();	break;
    	}
    	
    	this.buttonGroupFrequency2.clearSelection();
    	switch (this.test.getCourse().getFrequencyEnum2()) {
    	case A:		this.jRadioButtonP1FreqencyCode2A.doClick();	break;
    	case B:		this.jRadioButtonP1FreqencyCode2B.doClick();	break;
    	case C:		this.jRadioButtonP1FreqencyCode2C.doClick();	break;
    	default:	this.jRadioButtonP1FreqencyCode2D.doClick();	break;
    	}
    	
    	this.jComboBoxP1FrequencyAlert.setSelectedIndex(this.test.getCourse().getFrequencyAlert().ordinal());
   	
    	switch (this.test.getCourse().getShowResponseGrid()) {
    	case HIDE:	this.jRadioButtonP1HideGrid.doClick();	break;
    	default:	this.jRadioButtonP1ShowGrid.doClick();	break;	
    	}
    	
    	switch (this.test.getCourse().getShowResponsePattern()) {
    	case ICLICKERID:	this.jRadioButtonP1ShowGridClickerId.doClick();	break;
    	default:			this.jRadioButtonP1ShowGridStudentId.doClick();	break;
    	}
    	
    	this.jCheckBoxP1ShowChoice.setSelected(this.test.getCourse().isShowChoice());
    	this.jCheckBoxP1ShowAttempts.setSelected(this.test.getCourse().isShowAttempts());
    	
    	// Polling
    	
    	this.buttonGroupPollingTimer.clearSelection();
    	switch (this.test.getCourse().getTimerMode()) {
    	case UP: this.jRadioButtonP2Up.doClick();	break;
    	default: this.jRadioButtonP2Down.doClick();	break;
    	}
    	
    	this.jComboBoxP2DownTime.setSelectedIndex(this.test.getCourse().getPollingTimer().ordinal());
    	
    	// Results
    	
    	this.buttonGroupShowCorrectAnswer.clearSelection();
    	switch (this.test.getCourse().getCorrectAnswerDisplay()) {
    	case SHOW:	this.jRadioButtonP3Auto.doClick(); break;
    	default:	this.jRadioButtonP3Manual.doClick(); break;
    	}
    	
    	// Scoring
    	
    	this.jTextFieldP4SessionParticipationPoints.setText(Integer.toString(this.test.getCourse().getSessionParticipationPoints()));
    	
    	this.jComboBoxP4ParticipationPointsRequirement.setSelectedIndex(this.test.getCourse().getParticipationRequirement().ordinal());
    	
    	this.jTextFieldP4ParticipationBarValue.setText(Integer.toString(this.test.getCourse().getParticipationBarValue()));
    	
    	this.jTextFieldP4PointsForResponding.setText(Integer.toString(this.test.getCourse().getRespondingPoints()));
    	this.jTextFieldP4PointsForCorrect.setText(Integer.toString(this.test.getCourse().getCorrectRespondingPoints()));
    	
    	this.jCheckBoxP4TotalLimitEnabled.setSelected(this.test.getCourse().isSessionPointsLimit());
    	
    	this.jTextFieldP4TotalLimit.setEnabled(this.test.getCourse().isSessionPointsLimit());
    	
    	this.jTextFieldP4TotalLimit.setText(this.test.getCourse().getTotalPerformancePoints() == Integer.MAX_VALUE ? "" :
    			Integer.toString(this.test.getCourse().getTotalPerformancePoints()));
    	
    	this.jTextFieldP4PerformanceBarValue.setText(Integer.toString(this.test.getCourse().getPerformanceBarValue()));
    	
    	// Base Display
    	
    	switch (this.test.getCourse().getMultipleChoiceDisplay()) {
    	case PERCENTAGE: 	this.jRadioButtonP5Percentage.doClick(); break;
    	case NUMBER: 		this.jRadioButtonP5Number.doClick(); break;
    	default: 			this.jRadioButtonP5Alternating.doClick(); break;
    	}
    	
    	this.jComboBoxP5AlternateTime.setSelectedIndex(this.test.getCourse().getMultipleChoiceAlternateTime().ordinal());
    	
    	// Demographics
    	
    	this.jCheckBoxP6AutoAdvance.setSelected(this.test.getCourse().isAutoAdvanceCheck());

    	this.jComboBoxP6AutoAdvanceTime.setSelectedIndex(this.test.getCourse().getAutoAdvanceCheckTime().ordinal());
    }
    
    /**
     * Change configuration for the session fields.
     */
    private void writeConfiguration() {
    	// General
    	
    	this.test.getCourse().setInstructorID(this.jTextFieldP1Instructor.getText());
    	
    	if (this.jRadioButtonP1FreqencyCode1A.isSelected()) {
    		this.test.getCourse().setFrequencyEnum1(FrequencyEnum.A);
    	} else if (this.jRadioButtonP1FreqencyCode1B.isSelected()) {
    		this.test.getCourse().setFrequencyEnum1(FrequencyEnum.B);
    	} else if (this.jRadioButtonP1FreqencyCode1C.isSelected()) {
    		this.test.getCourse().setFrequencyEnum1(FrequencyEnum.C);
    	} else {
    		this.test.getCourse().setFrequencyEnum1(FrequencyEnum.D);
    	}
    	
    	if (this.jRadioButtonP1FreqencyCode2A.isSelected()) {
    		this.test.getCourse().setFrequencyEnum2(FrequencyEnum.A);
    	} else if (this.jRadioButtonP1FreqencyCode2B.isSelected()) {
    		this.test.getCourse().setFrequencyEnum2(FrequencyEnum.B);
    	} else if (this.jRadioButtonP1FreqencyCode2C.isSelected()) {
    		this.test.getCourse().setFrequencyEnum2(FrequencyEnum.C);
    	} else {
    		this.test.getCourse().setFrequencyEnum2(FrequencyEnum.D);
    	}
    	
    	this.test.getCourse().setFrequencyAlert(FrequencyAlert.values()[this.jComboBoxP1FrequencyAlert.getSelectedIndex()]);
    	    	
    	if (this.jRadioButtonP1HideGrid.isSelected()) {
    		this.test.getCourse().setShowResponseGrid(ShowResponseGrid.HIDE);
    	} else {
    		this.test.getCourse().setShowResponseGrid(ShowResponseGrid.SHOW);
    	}
    	
    	if (this.jRadioButtonP1ShowGridClickerId.isSelected()) {
    		this.test.getCourse().setShowResponsePattern(ShowResponsePattern.ICLICKERID);
    	} else {
    		this.test.getCourse().setShowResponsePattern(ShowResponsePattern.STUDENTID);
    	}
    	
    	this.test.getCourse().setShowChoice(this.jCheckBoxP1ShowChoice.isSelected() ? true : false);
    	
    	this.test.getCourse().setShowAttempts(this.jCheckBoxP1ShowAttempts.isSelected() ? true : false);
    	
    	// Polling
    	
    	if (this.jRadioButtonP2Up.isSelected()) {
    		this.test.getCourse().setTimerMode(TimerMode.UP);
    	} else {
    		this.test.getCourse().setTimerMode(TimerMode.DOWN);
    	}
    	
    	this.test.getCourse().setPollingTimer(PollingTimer.values()[this.jComboBoxP2DownTime.getSelectedIndex()]);
    	
    	// Results
    	
    	if (this.jRadioButtonP3Auto.isSelected()) {
    		this.test.getCourse().setCorrectAnswerDisplay(CorrectAnswerDisplay.SHOW);
    	} else {
    		this.test.getCourse().setCorrectAnswerDisplay(CorrectAnswerDisplay.HIDE);
    	}
    	
    	// Scoring
    	
    	if (this.jTextFieldP4SessionParticipationPoints.getText().equals(""))
    		this.test.getCourse().setSessionParticipationPoints(0);
    	else
    		this.test.getCourse().setSessionParticipationPoints(Integer.valueOf(this.jTextFieldP4SessionParticipationPoints.getText()));
    		
    	this.test.getCourse().setParticipationRequirement(ParticipationRequirement.values()[this.jComboBoxP4ParticipationPointsRequirement.getSelectedIndex()]);

    	if (this.jTextFieldP4ParticipationBarValue.getText().equals(""))
    		this.test.getCourse().setParticipationBarValue(0);
    	else
    		this.test.getCourse().setParticipationBarValue(Integer.valueOf(this.jTextFieldP4ParticipationBarValue.getText()));
    	
    	if (this.jTextFieldP4PointsForResponding.getText().equals(""))
    		this.test.getCourse().setRespondingPoints(0);
    	else
    		this.test.getCourse().setRespondingPoints(Integer.valueOf(this.jTextFieldP4PointsForResponding.getText()));
    	
    	if (this.jTextFieldP4PointsForCorrect.getText().equals(""))
    		this.test.getCourse().setCorrectRespondingPoints(0);
    	else
    		this.test.getCourse().setCorrectRespondingPoints(Integer.valueOf(this.jTextFieldP4PointsForCorrect.getText()));
    	
    	this.test.getCourse().setSessionPointsLimit(this.jCheckBoxP4TotalLimitEnabled.isSelected() ? true : false);
    	
    	if (this.jTextFieldP4TotalLimit.getText().equals(""))
    		this.test.getCourse().setTotalPerformancePoints(Integer.MAX_VALUE);
    	else
    		this.test.getCourse().setTotalPerformancePoints(Integer.valueOf(this.jTextFieldP4TotalLimit.getText()));
    	
    	if (this.jTextFieldP4PerformanceBarValue.getText().equals(""))
    		this.test.getCourse().setPerformanceBarValue(0);
    	else
    		this.test.getCourse().setPerformanceBarValue(Integer.valueOf(this.jTextFieldP4PerformanceBarValue.getText()));
    	
    	// Base Display
    	
    	if (this.jRadioButtonP5Percentage.isSelected()) {
    		this.test.getCourse().setMultipleChoiceDisplay(MultipleChoiceDisplay.PERCENTAGE);
    	} else if (this.jRadioButtonP5Number.isSelected()) {
    		this.test.getCourse().setMultipleChoiceDisplay(MultipleChoiceDisplay.NUMBER);
    	} else {
    		this.test.getCourse().setMultipleChoiceDisplay(MultipleChoiceDisplay.BOTH);
    	}
    	
    	this.test.getCourse().setMultipleChoiceAlternateTime(MultipleChoiceAlternateTime.values()[this.jComboBoxP5AlternateTime.getSelectedIndex()]);
    	
    	// Demographics
    	    	
    	this.test.getCourse().setAutoAdvanceCheck(this.jCheckBoxP6AutoAdvance.isSelected() ? true : false);
    	
    	this.test.getCourse().setAutoAdvanceCheckTime(AutoAdvanceCheckTime.values()[this.jComboBoxP6AutoAdvanceTime.getSelectedIndex()]);
    }
    
    /**
     * Write configuration to the file system
     * @throws IOException 
     * @throws XMLStreamException 
     */
    private void storeConfiguration() throws IOException, XMLStreamException {
    	this.test.getCourse().writeConfig();
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {                                  
    	// Do nothing.
    }
    
    /**
     * Set the visible tab.
     */
    public void setDefaultTab() {
        this.jTabbedPane3.setSelectedIndex(0);
    }
    
    private Test test;
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFrequency1;
    private javax.swing.ButtonGroup buttonGroupFrequency2;
    private javax.swing.ButtonGroup buttonGroupMultipleChoiceDisplay;
    private javax.swing.ButtonGroup buttonGroupPollingTimer;
    private javax.swing.ButtonGroup buttonGroupShowCorrectAnswer;
    private javax.swing.ButtonGroup buttonGroupShowID;
    private javax.swing.ButtonGroup buttonGroupShowResponseGrid;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonP6Delete;
    private javax.swing.JButton jButtonP6Edit;
    private javax.swing.JButton jButtonP6Import;
    private javax.swing.JButton jButtonP6MoveDown;
    private javax.swing.JButton jButtonP6MoveUp;
    private javax.swing.JButton jButtonP6New;
    private javax.swing.JButton jButtonP6Select;
    private javax.swing.JButton jButtonP6Unselected;
    private javax.swing.JButton jButtonSetForCourse;
    private javax.swing.JButton jButtonSetForSession;
    private javax.swing.JCheckBox jCheckBoxP1ShowAttempts;
    private javax.swing.JCheckBox jCheckBoxP1ShowChoice;
    private javax.swing.JCheckBox jCheckBoxP4TotalLimitEnabled;
    private javax.swing.JCheckBox jCheckBoxP6AutoAdvance;
    private javax.swing.JComboBox<String> jComboBoxP1FrequencyAlert;
    private javax.swing.JComboBox<String> jComboBoxP2DownTime;
    private javax.swing.JComboBox<String> jComboBoxP4ParticipationPointsRequirement;
    private javax.swing.JComboBox<String> jComboBoxP5AlternateTime;
    private javax.swing.JComboBox<String> jComboBoxP6AutoAdvanceTime;
    private javax.swing.JLabel jLabelP1CourseName;
    private javax.swing.JLabel jLabelP1CourseNameStatic;
    private javax.swing.JLabel jLabelP1EightCharacters;
    private javax.swing.JLabel jLabelP1FrequencyAlertStatic;
    private javax.swing.JLabel jLabelP1FrequencyCode1;
    private javax.swing.JLabel jLabelP1FrequencyCode2;
    private javax.swing.JLabel jLabelP1FrequencyCodeStatic;
    private javax.swing.JLabel jLabelP1InstructorStatic;
    private javax.swing.JLabel jLabelP1ResponseGridStatic;
    private javax.swing.JLabel jLabelP2PollingMinSec;
    private javax.swing.JLabel jLabelP2PollingTimer;
    private javax.swing.JLabel jLabelP3CorrectAnswerDisplay;
    private javax.swing.JLabel jLabelP3PreAssigned;
    private javax.swing.JLabel jLabelP4EachQuestionStatic;
    private javax.swing.JLabel jLabelP4ParticipationBarPercent;
    private javax.swing.JLabel jLabelP4ParticipationBarValue;
    private javax.swing.JLabel jLabelP4ParticipationPointsRequirementStatic;
    private javax.swing.JLabel jLabelP4ParticipationPointsStatic;
    private javax.swing.JLabel jLabelP4PerformanceBarPercent;
    private javax.swing.JLabel jLabelP4PerformanceBarValue;
    private javax.swing.JLabel jLabelP4PerformancePointsStatic;
    private javax.swing.JLabel jLabelP4PointsAreAwardedStatic;
    private javax.swing.JLabel jLabelP4PointsForCorrectStatic;
    private javax.swing.JLabel jLabelP4PointsForRespondingStatic;
    private javax.swing.JLabel jLabelP4SessionParticipationPointsStatic;
    private javax.swing.JLabel jLabelP4TotalPointStatic;
    private javax.swing.JLabel jLabelP5A2EDisplay;
    private javax.swing.JLabel jLabelP5Alternate;
    private javax.swing.JLabel jLabelP5Second;
    private javax.swing.JLabel jLabelP6AvailableQuestions;
    private javax.swing.JLabel jLabelP6DemographicsMinSec;
    private javax.swing.JLabel jLabelP6SelectedQuestions;
    private javax.swing.JList<String> jListP6AvailableQuestions;
    private javax.swing.JList<String> jListP6SelectedQuestions;
    private javax.swing.JPanel jPanelBaseDisplay;
    private javax.swing.JPanel jPanelDemographics;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JPanel jPanelPolling;
    private javax.swing.JPanel jPanelResults;
    private javax.swing.JPanel jPanelScoring;
    private javax.swing.JRadioButton jRadioButtonP1FreqencyCode1A;
    private javax.swing.JRadioButton jRadioButtonP1FreqencyCode1B;
    private javax.swing.JRadioButton jRadioButtonP1FreqencyCode1C;
    private javax.swing.JRadioButton jRadioButtonP1FreqencyCode1D;
    private javax.swing.JRadioButton jRadioButtonP1FreqencyCode2A;
    private javax.swing.JRadioButton jRadioButtonP1FreqencyCode2B;
    private javax.swing.JRadioButton jRadioButtonP1FreqencyCode2C;
    private javax.swing.JRadioButton jRadioButtonP1FreqencyCode2D;
    private javax.swing.JRadioButton jRadioButtonP1HideGrid;
    private javax.swing.JRadioButton jRadioButtonP1ShowGrid;
    private javax.swing.JRadioButton jRadioButtonP1ShowGridClickerId;
    private javax.swing.JRadioButton jRadioButtonP1ShowGridStudentId;
    private javax.swing.JRadioButton jRadioButtonP3Auto;
    private javax.swing.JRadioButton jRadioButtonP3Manual;
    private javax.swing.JRadioButton jRadioButtonP5Alternating;
    private javax.swing.JRadioButton jRadioButtonP5Number;
    private javax.swing.JRadioButton jRadioButtonP5Percentage;
    private javax.swing.JRadioButton jRadioButtonP2Down;
    private javax.swing.JRadioButton jRadioButtonP2Up;
    private javax.swing.JScrollPane jScrollPaneP6AvailableQuestions;
    private javax.swing.JScrollPane jScrollPaneP6SelectedQuestions;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextFieldP1Instructor;
    private javax.swing.JTextField jTextFieldP4ParticipationBarValue;
    private javax.swing.JTextField jTextFieldP4PerformanceBarValue;
    private javax.swing.JTextField jTextFieldP4PointsForCorrect;
    private javax.swing.JTextField jTextFieldP4PointsForResponding;
    private javax.swing.JTextField jTextFieldP4SessionParticipationPoints;
    private javax.swing.JTextField jTextFieldP4TotalLimit;
    // End of variables declaration//GEN-END:variables
    
}
