package gui;

import java.io.File;

import javax.swing.JOptionPane;

import content.Course;

import app.*;

/**
 * New course dialog.
 * @author Junhao
 */
@SuppressWarnings("serial")
public class NewCourse extends javax.swing.JFrame {

    /**
     * Create new form NewCourse.
     */
    public NewCourse(Test test) {
        this.test = test;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCourseName = new javax.swing.JTextField();
        jButtonCreate = new javax.swing.JButton();
        jTextFieldCourseNumber = new javax.swing.JTextField();
        jTextFieldSectionNumber = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        this.setResizable(false);
        this.setTitle("New Course");
        
        jTextFieldCourseName.setText("\n");

        jButtonCreate.setText("Create");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonCreateActionPerformed(evt);
				} catch (Exception e) {
					e.printStackTrace();
				}
            }
        });

        jTextFieldCourseNumber.setText("\n");

        jTextFieldSectionNumber.setText("\n");

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        jLabel1.setText("Add your course information.");

        jLabel2.setText("Your course information should be specific enough so that your ");

        jLabel5.setText("Course Number:");

        jLabel6.setText("Section Number:");

        jLabel3.setText("students can use it to identify your course.");

        jLabel4.setText("Course Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldSectionNumber)
                                    .addComponent(jTextFieldCourseNumber)
                                    .addComponent(jTextFieldCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCreate)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldCourseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldSectionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonCreate))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_jButtonCreateActionPerformed
        // Button Create
    	
    	// Obtain text field containing course name, course number and section number.
        String courseName = jTextFieldCourseName.getText().trim();
        String courseNumber = jTextFieldCourseNumber.getText().trim();
        String sectionNumber = jTextFieldSectionNumber.getText().trim();
        
        // Check if at least one field is filled.
        if (courseName.equals("") && courseNumber.equals("") && sectionNumber.equals("")) {
        	JOptionPane.showMessageDialog(this, "Please fill at least one of the three fields to create a course", "Empty Course Information!", JOptionPane.ERROR_MESSAGE);
        	return;
        }
        
        // Check if illegal characters exist.
        if (Course.ifTextLegal(courseName) == false || Course.ifTextLegal(courseNumber) == false || Course.ifTextLegal(sectionNumber) == false) {
        	JOptionPane.showMessageDialog(this, "Only A-Z, a-z, 0-9 and space are allowed.", "Illegal Characters Detected!", JOptionPane.ERROR_MESSAGE);
        	return;
        }
        
        // Generate the name of the folder representing this course.
        String finalName = courseName
                + (courseNumber.equals("") ? "" : "-") + courseNumber
                + (sectionNumber.equals("") ? "" : "-") + sectionNumber;
        
        // Check if the course already exists.
		String coursePath = "./Classes/" + finalName;

		File file = new File(coursePath);
	    
	    if (file.exists()) {
        	JOptionPane.showMessageDialog(this, "Course with the same name exists. Please use a new name.", "Course Exists!", JOptionPane.ERROR_MESSAGE);
        	return;
	    }

        // Create course in the file system.
	    Course.createCourse(finalName);
	    
	    // Update course list in Welcome window.
        test.getWelcome().updateCourseList();
        
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // Button Cancel
    	
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    /**
     * Clear all fields when the dialog is launched.
     */
    public void clearFields() {
        this.jTextFieldCourseName.setText("");
        this.jTextFieldCourseNumber.setText("");
        this.jTextFieldSectionNumber.setText("");
    }
    
    private Test test;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldCourseName;
    private javax.swing.JTextField jTextFieldCourseNumber;
    private javax.swing.JTextField jTextFieldSectionNumber;
    // End of variables declaration//GEN-END:variables
}
