package gui;

import utility.MultipleScreens;
import utility.SetLocation;
import content.QuestionBody;
import app.Test;

/**
 * Panel showing a question.
 * @author Junhao
 */
@SuppressWarnings("serial")
public class QuestionPanel extends javax.swing.JFrame {

    /**
     * Creates new form QuestionPanel
     */
    public QuestionPanel(Test test) {
    	this.test = test;
        initComponents();
        
        int screenCount = MultipleScreens.getNumberOfScreens();
        SetLocation.setTopRight(this, screenCount - 1, 20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelA = new javax.swing.JLabel();
        jLabelB = new javax.swing.JLabel();
        jLabelC = new javax.swing.JLabel();
        jLabelD = new javax.swing.JLabel();
        jLabelE = new javax.swing.JLabel();
        jLabelAChoice = new javax.swing.JLabel();
        jLabelBChoice = new javax.swing.JLabel();
        jLabelCChoice = new javax.swing.JLabel();
        jLabelDChoice = new javax.swing.JLabel();
        jLabelEChoice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        this.setResizable(false);
        this.setTitle("Question Panel");
        
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("jLabel1");
        jLabelTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelA.setText("A:");

        jLabelB.setText("B:");

        jLabelC.setText("C:");

        jLabelD.setText("D:");

        jLabelE.setText("E:");

        jLabelAChoice.setText("jLabel7");

        jLabelBChoice.setText("jLabel8");

        jLabelCChoice.setText("jLabel9");

        jLabelDChoice.setText("jLabel10");

        jLabelEChoice.setText("jLabel11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelE, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelD, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelC, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelA, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelEChoice, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                            .addComponent(jLabelDChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelAChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelBChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelA)
                    .addComponent(jLabelAChoice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelB)
                    .addComponent(jLabelBChoice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelC)
                    .addComponent(jLabelCChoice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelD)
                    .addComponent(jLabelDChoice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelE)
                    .addComponent(jLabelEChoice))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    public void loadListQuestion(QuestionBody questionBody) {
    	this.jLabelTitle.setText(questionBody.getTitle());
    	this.jLabelAChoice.setText(questionBody.getChoiceA());
    	this.jLabelBChoice.setText(questionBody.getChoiceB());
    	this.jLabelCChoice.setText(questionBody.getChoiceC());
    	this.jLabelDChoice.setText(questionBody.getChoiceD());
    	this.jLabelEChoice.setText(questionBody.getChoiceE());
    }
    
    public void loadOnTheFlyQuestion(QuestionBody questionBody) {
    	this.jLabelTitle.setText(questionBody.getBody());
    	this.jLabelAChoice.setText(questionBody.getChoiceA());
    	this.jLabelBChoice.setText(questionBody.getChoiceB());
    	this.jLabelCChoice.setText(questionBody.getChoiceC());
    	this.jLabelDChoice.setText(questionBody.getChoiceD());
    	this.jLabelEChoice.setText(questionBody.getChoiceE());
    }
    
    Test test;
    
    // Variables declaration - do not modify
    private javax.swing.JLabel jLabelA;
    private javax.swing.JLabel jLabelAChoice;
    private javax.swing.JLabel jLabelB;
    private javax.swing.JLabel jLabelBChoice;
    private javax.swing.JLabel jLabelC;
    private javax.swing.JLabel jLabelCChoice;
    private javax.swing.JLabel jLabelD;
    private javax.swing.JLabel jLabelDChoice;
    private javax.swing.JLabel jLabelE;
    private javax.swing.JLabel jLabelEChoice;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration
}
