package gui;

import gui.enumoption.EnumCorrectAnswer;
import app.Test;

/**
 * Setting correct answer dialog.
 * @author Junhao
 */
@SuppressWarnings("serial")
public class SelectCorrect extends javax.swing.JFrame {

    /**
     * Creates new form SelectCorrect.
     */
    public SelectCorrect(Test test) {
        this.test = test;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jCheckBoxA = new javax.swing.JCheckBox();
        jCheckBoxE = new javax.swing.JCheckBox();
        jCheckBoxD = new javax.swing.JCheckBox();
        jCheckBoxC = new javax.swing.JCheckBox();
        jCheckBoxB = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonCancel = new javax.swing.JButton();
        jButtonApply = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();

        this.setResizable(false);
        this.setTitle("Set Correct Answer");
        
        jLabel4.setText("Select the student response that is correct");

        buttonGroup1.add(jCheckBoxA);
        jCheckBoxA.setText("A");

        buttonGroup1.add(jCheckBoxE);
        jCheckBoxE.setText("E");

        buttonGroup1.add(jCheckBoxD);
        jCheckBoxD.setText("D");

        buttonGroup1.add(jCheckBoxC);
        jCheckBoxC.setText("C");

        buttonGroup1.add(jCheckBoxB);
        jCheckBoxB.setText("B");

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonApply.setText("Apply");
        jButtonApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplyActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonClear)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonApply)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancel)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxB)
                    .addComponent(jCheckBoxA)
                    .addComponent(jCheckBoxC)
                    .addComponent(jCheckBoxD)
                    .addComponent(jCheckBoxE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxA)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxB)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxC)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxD)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonApply)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // Button Cancel
    	
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplyActionPerformed
       // Button Apply
    	
        EnumCorrectAnswer enumCorrectAnswer;
        
        if (this.jCheckBoxA.isSelected()) {
            enumCorrectAnswer = EnumCorrectAnswer.A;
        } else if (this.jCheckBoxB.isSelected()){
            enumCorrectAnswer = EnumCorrectAnswer.B;
        } else if (this.jCheckBoxC.isSelected()){
            enumCorrectAnswer = EnumCorrectAnswer.C;
        } else if (this.jCheckBoxD.isSelected()){
            enumCorrectAnswer = EnumCorrectAnswer.D;
        } else if (this.jCheckBoxE.isSelected()){
            enumCorrectAnswer = EnumCorrectAnswer.E;
        } else {
            enumCorrectAnswer = EnumCorrectAnswer.NA;
        }
        
        this.test.getCourse().getSession().getCurrentQuestion().setCorrectAnswer(enumCorrectAnswer);
        
        this.test.getHistogramInstructor().update();
        this.test.getHistogramStudent().update();
		
		this.setVisible(false);
    }//GEN-LAST:event_jButtonApplyActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // Button Clear
    	
        this.buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButtonClearActionPerformed
    
    /**
     * Reset selection.
     */
    public void resetSelectCorrect() {
    	this.buttonGroup1.clearSelection();
    }
    
    private Test test;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonApply;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JCheckBox jCheckBoxA;
    private javax.swing.JCheckBox jCheckBoxB;
    private javax.swing.JCheckBox jCheckBoxC;
    private javax.swing.JCheckBox jCheckBoxD;
    private javax.swing.JCheckBox jCheckBoxE;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
