package gui;

import java.io.File;
import java.io.IOException;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

import content.enumoption.HistogramDisplayOption;

import utility.MultipleScreens;
import utility.SetLocation;

import app.Test;

/**
 * Start session window.
 * @author Junhao
 *
 */
@SuppressWarnings("serial")
public class StartSession extends javax.swing.JFrame {
    
    /**
     * Create new form StartSession.
     */
    public StartSession(Test test) {
        this.test = test;
        initComponents();
        SetLocation.setCenterScreen(this, 0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSettings = new javax.swing.JButton();
        jLabelCourseName = new javax.swing.JLabel();
        jLabelClickerPP = new javax.swing.JLabel();
        jButtonStart = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonChangeCourse = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuFileItemExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuEditItemSettings = new javax.swing.JMenuItem();
        jMenuSession = new javax.swing.JMenu();
        jMenuSessionItemStart = new javax.swing.JMenuItem();
        jMenuQuestion = new javax.swing.JMenu();
        jMenuQuestionItemNew = new javax.swing.JMenuItem();
        jMenuQuestionItemOpen = new javax.swing.JMenuItem();
        jMenuCourse = new javax.swing.JMenu();
        jMenuCourseItemChange = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuHelpItemAbout = new javax.swing.JMenuItem();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setTitle("Start Session");

        jButtonSettings.setText("My Settings");
        jButtonSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingsActionPerformed(evt);
            }
        });

        jLabelCourseName.setText("course name");

        jLabelClickerPP.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
        jLabelClickerPP.setText("Clicker++");

        jButtonStart.setText("Start Session");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonStartActionPerformed(evt);
				} catch (Exception e) {
					e.printStackTrace();
				}
            }
        });

        jButtonChangeCourse.setText("Change Course");
        jButtonChangeCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeCourseActionPerformed(evt);
            }
        });

        jMenuFile.setText("File");

        jMenuFileItemExit.setText("Exit");
        jMenuFileItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuFileItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Edit");

        jMenuEditItemSettings.setText("My Settings");
        jMenuEditItemSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditItemSettingsActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuEditItemSettings);

        jMenuBar1.add(jMenuEdit);

        jMenuSession.setText("Session");

        jMenuSessionItemStart.setText("Start Session");
        jMenuSessionItemStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jMenuSessionItemStartActionPerformed(evt);
				} catch (Exception e) {
					e.printStackTrace();
				}
            }
        });
        jMenuSession.add(jMenuSessionItemStart);

        jMenuBar1.add(jMenuSession);

        jMenuQuestion.setText("Question");

        jMenuQuestionItemNew.setText("New Question List");
        jMenuQuestionItemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuestionItemNewActionPerformed(evt);
            }
        });
        jMenuQuestion.add(jMenuQuestionItemNew);

        jMenuQuestionItemOpen.setText("Open Question List");
        jMenuQuestionItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jMenuQuestionItemOpenActionPerformed(evt);
				} catch (IOException e) {
					e.printStackTrace();
				}
            }
        });
        jMenuQuestion.add(jMenuQuestionItemOpen);
        
        jMenuBar1.add(jMenuQuestion);

        jMenuCourse.setText("Course");

        jMenuCourseItemChange.setText("Change Course");
        jMenuCourseItemChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCourseItemChangeActionPerformed(evt);
            }
        });
        jMenuCourse.add(jMenuCourseItemChange);

        jMenuBar1.add(jMenuCourse);
        
        jMenuHelp.setText("Help");

        jMenuHelpItemAbout.setText("About");
        jMenuHelpItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHelpItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuHelpItemAbout);
        
        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(32, 32, 32)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(jButtonChangeCourse)
                                        .add(0, 407, Short.MAX_VALUE))
                                    .add(layout.createSequentialGroup()
                                        .add(jLabelCourseName)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(jLabelClickerPP))))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator2)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator1))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jButtonSettings, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 225, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .add(layout.createSequentialGroup()
                .add(42, 42, 42)
                .add(jButtonStart, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 231, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelClickerPP)
                    .add(jLabelCourseName))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonChangeCourse)
                .add(18, 18, 18)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonStart, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonSettings, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_jButtonStartActionPerformed
        // Button Start Session
    	
    	this.test.getCourse().createSession();
        this.setVisible(false);
        
        int screenCount = MultipleScreens.getNumberOfScreens();
        
        ToolbarInstructor toolbarInstructor = test.getToolbarInstructor();
        SetLocation.setTopLeft(toolbarInstructor, 0, 10);
        toolbarInstructor.setVisible(true);
        	
        ToolbarStudent toolbarStudent = test.getToolbarStudent();
        SetLocation.setTopLeft(toolbarStudent, screenCount - 1, 10);
        toolbarStudent.setVisible(false);
        
        this.test.getHistogramInstructor().setHistogramDisplayOption(HistogramDisplayOption.SHOWWITHCORRECTANSWER);
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettingsActionPerformed
        // Button My Settings
    	
        test.getMySettings().readConfiguration();
        test.getMySettings().setDefaultTab();
        SetLocation.setCenterScreen(test.getMySettings(), 0);
        test.getMySettings().setVisible(true);        
    }//GEN-LAST:event_jButtonSettingsActionPerformed

    private void jButtonChangeCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeCourseActionPerformed
        // Button Change Course
    	
        this.setVisible(false);
        SetLocation.setCenterScreen(test.getWelcome(), 0);
        test.getWelcome().setVisible(true);
    }//GEN-LAST:event_jButtonChangeCourseActionPerformed

    private void jMenuFileItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFileItemExitActionPerformed
        // File Exit
    	
        System.exit(0);
    }//GEN-LAST:event_jMenuFileItemExitActionPerformed

    private void jMenuEditItemSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditItemSettingsActionPerformed
        // Edit My Settings
    	
        test.getMySettings().readConfiguration();
        test.getMySettings().setDefaultTab();
        SetLocation.setCenterScreen(test.getMySettings(), 0);
        test.getMySettings().setVisible(true);
    }//GEN-LAST:event_jMenuEditItemSettingsActionPerformed

    private void jMenuSessionItemStartActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_jMenuSessionItemStartActionPerformed
        // Session Start Session
    	
    	this.test.getCourse().createSession();
        this.setVisible(false);

        int screenCount = MultipleScreens.getNumberOfScreens();
        
        ToolbarInstructor toolbarInstructor = test.getToolbarInstructor();
        SetLocation.setTopLeft(toolbarInstructor, 0, 10);
        toolbarInstructor.setVisible(true);
        	
        ToolbarStudent toolbarStudent = test.getToolbarStudent();
        SetLocation.setTopLeft(toolbarStudent, screenCount - 1, 10);
        toolbarStudent.setVisible(false);
    }//GEN-LAST:event_jMenuSessionItemStartActionPerformed

    private void jMenuQuestionItemNewActionPerformed(java.awt.event.ActionEvent evt) {
        // Question New Question List
    	
    	this.test.getQuestionList().clearList();
    	this.test.getQuestionList().clearFields();
    	this.test.getQuestionList().setFocusToTitle();
    	this.test.getQuestionList().setVisible(true);
    	this.test.getQuestionList().clearListQuestionPath();
    }

    private void jMenuQuestionItemOpenActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
        // Question Open Question List
    	
    	JFileChooser jFileChooser = new JFileChooser();
    	jFileChooser.setCurrentDirectory(new java.io.File("./Classes/" + this.test.getCourse().getCourseName()));
    	jFileChooser.setAcceptAllFileFilterUsed(false);
    	jFileChooser.addChoosableFileFilter(new FileNameExtensionFilter(".csv Files", new String[] { "csv" }));
    	
    	int returnVal = jFileChooser.showOpenDialog(this);
    	
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser.getSelectedFile();
            this.test.getQuestionList().loadList(file.getPath());
        } else {
        	return;
        }
        
        this.test.getQuestionList().setFocusToTitle();
        this.test.getQuestionList().setVisible(true);
    }
    
    private void jMenuCourseItemChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCourseItemChangeActionPerformed
        // Course Change Course
    	
        this.setVisible(false);
        SetLocation.setCenterScreen(test.getWelcome(), 0);
        test.getWelcome().setVisible(true);
    }//GEN-LAST:event_jMenuCourseItemChangeActionPerformed
    
    private void jMenuHelpItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHelpItemAboutActionPerformed
        // Help About
    	
    	SetLocation.setCenterScreen(test.getAbout(), 0);
    	test.getAbout().setVisible(true);
        
    }//GEN-LAST:event_jMenuHelpItemAboutActionPerformed
    
    /**
     * Change the course name displayed on the form.
     * @param name course name.
     */
    public void setCourseName(String name) {
    	if (name.length() <= 15) {
    		this.jLabelCourseName.setText(name);
    	}
    	else {
    		this.jLabelCourseName.setText(name.substring(0, 15) + "...");
    	}
    }
    
    private Test test;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChangeCourse;
    private javax.swing.JButton jButtonSettings;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JLabel jLabelClickerPP;
    private javax.swing.JLabel jLabelCourseName;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCourse;
    private javax.swing.JMenuItem jMenuCourseItemChange;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenuItem jMenuEditItemSettings;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuFileItemExit;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuHelpItemAbout;
    private javax.swing.JMenu jMenuQuestion;
    private javax.swing.JMenuItem jMenuQuestionItemNew;
    private javax.swing.JMenuItem jMenuQuestionItemOpen;
    private javax.swing.JMenu jMenuSession;
    private javax.swing.JMenuItem jMenuSessionItemStart;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
    
}
