package gui;

import java.util.Vector;

import utility.SetLocation;

import app.Test;
import content.*;

/**
 * Welcome window.
 * @author Junhao
 *
 */
@SuppressWarnings("serial")
public class Welcome extends javax.swing.JFrame {
    
    /**
     * Create new form Welcome.
     */
    public Welcome(Test test) {
        this.test = test;
        this.courseList = Course.getCourseList();
        initComponents();
        SetLocation.setCenterScreen(this, 0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings({ })
	private void initComponents() {

        jButtonExit = new javax.swing.JButton();
        jButtonChoose = new javax.swing.JButton();
        jLabelChooseYourCourse = new javax.swing.JLabel();
        jLabeliClickerPP = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<String>(courseList);
        jButtonNew = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setTitle("Welcome to Clicker++");
        
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonChoose.setText("Choose");
        jButtonChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonChooseActionPerformed(evt);
				} catch (Exception e) {
					e.printStackTrace();
				}
            }
        });

        jLabelChooseYourCourse.setText("Choose your course:");

        jLabeliClickerPP.setText("Clicker++");

        jScrollPane3.setViewportView(jList3);

        jButtonNew.setText("New");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane3)
                    .add(layout.createSequentialGroup()
                        .add(jLabelChooseYourCourse)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabeliClickerPP))
                    .add(layout.createSequentialGroup()
                        .add(jButtonNew, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jButtonEdit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jButtonDelete)
                        .add(0, 325, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jButtonChoose)
                        .add(18, 18, 18)
                        .add(jButtonExit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .add(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelChooseYourCourse)
                    .add(jLabeliClickerPP))
                .add(18, 18, 18)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonNew)
                    .add(jButtonEdit)
                    .add(jButtonDelete))
                .add(19, 19, 19)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonChoose)
                    .add(jButtonExit))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        // Button New
    	
        test.getNewCourse().clearFields();
        SetLocation.setCenterParent(this, test.getNewCourse());
        test.getNewCourse().setVisible(true);
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // Button Edit
    	
        String editName = (String)jList3.getSelectedValue();
        if (editName == null) return;
        
        test.getEditCourse().setFields(editName);
        SetLocation.setCenterParent(this, test.getEditCourse());
        test.getEditCourse().setVisible(true);
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // Button Delete
    	
        String deleteName = (String)jList3.getSelectedValue();
        if (deleteName == null) return;
        
        test.getDeleteCourse().setFields(deleteName);
        SetLocation.setCenterParent(this, test.getDeleteCourse());
        test.getDeleteCourse().setVisible(true);
    }//GEN-LAST:event_jButtonDeleteActionPerformed
    
    private void jButtonChooseActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_jButtonChooseActionPerformed
        // Button Choose
    	
        String courseName = (String)jList3.getSelectedValue();
        if (courseName == null) return;
        
        test.LoadCourse(courseName);
        test.getStartSession().setCourseName(courseName);
        this.setVisible(false);
        test.getStartSession().setVisible(true);
    }//GEN-LAST:event_jButtonChooseActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // Button Exit
    	
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * Update the list of courses in the Welcome dialog.
     */
    public void updateCourseList() {
    	this.courseList = Course.getCourseList();
    	jList3 = new javax.swing.JList<String>(courseList);
    	jScrollPane3.setViewportView(jList3);
    }
            
    private Vector<String> courseList;
    private Test test;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChoose;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JLabel jLabelChooseYourCourse;
    private javax.swing.JLabel jLabeliClickerPP;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
    
}
